version: '3.2'

services:
  app:
    build: .
    image: new-app:latest
    restart: unless-stopped
    volumes:
      - type: volume
        source: new-app
        target: /usr/src/app/storage
    environment:
      MONGODB_HOST: mongo
      MONGODB_DATABASE: new-app
    ports:
      - "80:8080"
    networks:
      - new-app
    depends_on:
      - mongo

  mongo:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - type: volume
        source: mongo-data-db
        target: /data/db
    ports:
      - "27017:27017"
    networks:
      - new-app

volumes:
  new-app:
  mongo-data-db:

networks:
  new-app:

